# Generated by Django 5.2.5 on 2025-10-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer')], default='customer', max_length=20),
        ),
    ]
