# Generated by Django 5.2.5 on 2025-10-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_userprofile_agree_terms_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
