# Generated by Django 5.2.5 on 2025-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0005_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
