# Generated by Django 5.2.5 on 2025-10-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0006_userprofile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
    ]
